version: '3.8'
services:
  go-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.20-bullseye
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep 999d

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 9432:5432
    volumes:
      - ../db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080
